name: impostor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Rango de SDK más compatible

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.6
  rive: ^0.13.4 # Versión más reciente y compatible con el SDK
  provider: ^6.1.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/videos/
    - assets/rive/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
